package test
import com.drools.model.Customer
rule "rule1"
    salience 3
    agenda-group "test"
    when
        $customer:Customer(age>30, gender)
    then
       System.out.println("年龄大于30的，老男人"+$customer.getName());
end



rule "rule2"
    salience 2
    agenda-group "test"
    when
        $customer:Customer(age<28, !gender,age>18)
    then
       System.out.println("18到28，小美女"+$customer.getName());
end

rule "rule3"
    salience 1
    agenda-group "test"
    when
        $customer:Customer(gender)
    then
       //只要是男性都会执行此处
       System.out.println("男的"+$customer.getName());
end

